# Generated by Django 2.0.2 on 2018-03-22 17:51

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login', models.CharField(help_text='Login', max_length=200)),
                ('budget_month', models.PositiveSmallIntegerField(default=0, help_text='Format: <MM>', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('budget_year', models.PositiveSmallIntegerField(default=2018, help_text='Format: <YYYY>', validators=[django.core.validators.MinValueValidator(2017), django.core.validators.MaxValueValidator(2050)])),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_info', models.CharField(help_text='Buchungs Info', max_length=200)),
                ('budget_booked', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Budget_Pos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.SmallIntegerField(default=1)),
                ('booking_date', models.DateTimeField(default=datetime.datetime(2018, 3, 22, 18, 51, 30, 568979))),
                ('booking_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('booking_info', models.CharField(help_text='Buchungs Info', max_length=200)),
                ('booking_booked', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('budget_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Budget')),
            ],
            options={
                'ordering': ['budget_id', '-pos'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='budget_pos',
            unique_together={('budget_id', 'pos')},
        ),
    ]
