# Generated by Django 2.0.2 on 2018-03-11 14:33

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('budget_month', models.PositiveSmallIntegerField(default=0, help_text='Format: <MM>', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('budget_year', models.PositiveSmallIntegerField(default=2018, help_text='Format: <YYYY>', validators=[django.core.validators.MinValueValidator(2017), django.core.validators.MaxValueValidator(2050)])),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_info', models.CharField(help_text='Buchungs Info', max_length=200)),
                ('budget_booked', models.DateTimeField(editable=False, verbose_name='date changed')),
            ],
        ),
        migrations.CreateModel(
            name='Budget_Pos',
            fields=[
                ('pos', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField(default=datetime.datetime(2018, 3, 11, 15, 33, 40, 462160))),
                ('booking_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('booking_info', models.CharField(help_text='Buchungs Info', max_length=200)),
                ('booking_booked', models.DateTimeField(editable=False, verbose_name='date changed')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Budget')),
            ],
            options={
                'ordering': ['id', 'pos'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='budget_pos',
            unique_together={('id', 'pos')},
        ),
    ]
