# Generated by Django 2.0.2 on 2018-03-25 16:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget_Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('budget_info', models.CharField(help_text='Buchungs Info', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='budget_pos',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 25, 18, 54, 6, 446883)),
        ),
    ]
