# Generated by Django 2.0.2 on 2018-03-25 18:09

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20180325_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget_base',
            name='budget_start_day',
            field=models.PositiveSmallIntegerField(default=0, help_text='Format: <MM>', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='budget_pos',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 25, 20, 9, 15, 226279)),
        ),
    ]
