# Generated by Django 2.0.2 on 2018-03-29 15:21

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20180325_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget_base',
            name='budget_start_day',
            field=models.PositiveSmallIntegerField(default=0, help_text='Format: <MM>', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='budget_base',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='budget_pos',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 29, 17, 21, 50, 994261)),
        ),
    ]
