# Generated by Django 2.0.2 on 2018-03-15 20:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20180315_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget_pos',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 15, 21, 55, 27, 793680)),
        ),
        migrations.AlterField(
            model_name='budget_pos',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='budget.Budget'),
        ),
        migrations.AlterField(
            model_name='budget_pos',
            name='pos',
            field=models.SmallIntegerField(default=1),
        ),
    ]
