# Generated by Django 2.0.2 on 2018-03-15 22:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20180315_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget_pos',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 15, 23, 34, 20, 899935)),
        ),
        migrations.AlterField(
            model_name='budget_pos',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Budget'),
        ),
        migrations.AlterField(
            model_name='budget_pos',
            name='pos',
            field=models.SmallIntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
